name: "Export Godot"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - release
      - staging

env:
  GODOT_VERSION: 3.4.4
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
  git_branch: ${{ github.ref_name }}

jobs:

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:linux
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/*
          tag: linux
          file_glob: true
          overwrite: true

  export-win:
    name: Windows Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:windows
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/*
          tag: windows
          file_glob: true
          overwrite: true

  export-osx:
    name: OSX Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:osx
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx
          path: build/osx
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/osx/*
          tag: osx
          file_glob: true
          overwrite: true
  

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      #- if: ${{ github.ref == 'refs/heads/release' }}
      - run: ./run export:web
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: gdlearn
          directory: build/web
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}